"""Configuration management for Libris (vault paths, API keys, settings)."""

import os
import secrets
from pathlib import Path
from typing import Any, Optional

import yaml

LEGACY_VAULT_KEY = "vault_path"
BOOK_VAULT_KEY = "book_vault"
# noqa justified: the name of a config key, not a credential. The token it
# points at is generated by ensure_server_token and never hardcoded.
SERVER_TOKEN_KEY = "server_token"  # noqa: S105
EXTENSION_ORIGINS_KEY = "extension_origins"


def get_config_dir() -> Path:
    env_config_dir = os.environ.get("LIBRIS_CONFIG_DIR")
    if env_config_dir:
        return Path(env_config_dir).expanduser().resolve()
    return Path.home() / ".config" / "libris"


def get_config_file() -> Path:
    return get_config_dir() / "config.yaml"


def get_config() -> dict:
    config_file = get_config_file()
    if not config_file.exists():
        return {}
    with open(config_file, "r") as f:
        return yaml.safe_load(f) or {}


def set_config(key: str, value: Any):
    config_dir = get_config_dir()
    config_dir.mkdir(parents=True, exist_ok=True)
    config = get_config()
    config[key] = value
    with open(get_config_file(), "w") as f:
        yaml.dump(config, f)


def set_book_vault_path(path: Path):
    resolved = str(path.expanduser().resolve())
    set_config(BOOK_VAULT_KEY, resolved)
    # Keep legacy key for backward compatibility with existing configs.
    set_config(LEGACY_VAULT_KEY, resolved)


def get_vault_path() -> Path:
    config = get_config()
    path_str = config.get(BOOK_VAULT_KEY) or config.get(LEGACY_VAULT_KEY)
    if not path_str:
        return Path(".").resolve()
    return Path(path_str).expanduser().resolve()


def is_vault_configured() -> bool:
    """Check whether a Shelf has actually been configured.

    `get_vault_path` falls back to the working directory when nothing is set
    (see #82), so "the path it returns exists" says nothing about whether a
    person chose it. The daemon needs the difference: it refuses to start
    without a Shelf, and `/health` reports it so a Surface can tell "running"
    from "usable" (ADR 0019).

    Returns:
        True when a vault path is set under either the current or legacy key.
    """
    config = get_config()
    return bool(config.get(BOOK_VAULT_KEY) or config.get(LEGACY_VAULT_KEY))


def get_api_key() -> Optional[str]:
    config = get_config()
    return config.get("google_books_api_key")


def get_obsidian_vault_root() -> Optional[Path]:
    """Get the Obsidian vault root path, or None if not configured."""
    config = get_config()
    path_str = config.get("obsidian_vault_root")
    if not path_str:
        return None
    return Path(path_str).expanduser().resolve()


def get_server_token() -> Optional[str]:
    """Get the daemon's bearer token, or None if one has never been generated."""
    config = get_config()
    token = config.get(SERVER_TOKEN_KEY)
    return token or None


def ensure_server_token() -> str:
    """Get the daemon's bearer token, generating and persisting one if absent.

    The token is persisted rather than regenerated per run, so restarting the
    daemon does not silently break an extension that already holds it.

    Returns:
        The bearer token the daemon accepts.
    """
    existing = get_server_token()
    if existing:
        return existing
    token = secrets.token_urlsafe(32)
    set_config(SERVER_TOKEN_KEY, token)
    return token


def get_extension_origins() -> list[str]:
    """Get the browser origins allowed to call the daemon.

    Returns:
        The configured origins, or an empty list. Empty means no cross-origin
        caller is allowed; the allowlist is never widened to "*", because the
        daemon is reachable from every page the browser has open.
    """
    config = get_config()
    origins = config.get(EXTENSION_ORIGINS_KEY) or []
    if isinstance(origins, str):
        return [origins]
    return list(origins)
